### ISSUE TITLE
[1.5] Base table or view not found on MySql 5.7

### ISSUE THREAD

**Issue by MrSnoozles** [rockettpw/jumplinks#16]
Hey Mike,

I wanted to try your module, but can't install it correctly. The SQL Queries that get executed fail for me (MySQL 5.7.13) because of the following error:

`A symbol name was expected! (near "source" at position 98)`

This is because "**source**" is a keyword, probably starting from MySql 5.7. https://dev.mysql.com/doc/refman/5.7/en/keywords.html

After installation I see the following error in the backend

`Modules: Failed to init module: ProcessJumplinks - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'stromvergleich.process_jumplinks' doesn't exist`

A quick fix for the issue would be to escape the field names in the sql files.

Thank you for your great work!

**Comment by mikerockett** [comment]
Hi @MrSnoozles, and thanks for reporting that. I develop with MariaDB and haven't encountered the issue there. Seems somewhat strange as if it is a keyword in MySQL 5.7, then it *should* be a keyword in MDB as well, for the purposes of keeping features between the two.

So you reckon if I change the schemas like this, it'll be okay?

```sql
CREATE TABLE IF NOT EXISTS <table-name> (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `source` VARCHAR(512) NOT NULL,
    `destination` VARCHAR(512) NOT NULL,
    `hits` INT UNSIGNED DEFAULT 0,
    `user_created` INT UNSIGNED DEFAULT 0,
    `user_updated` INT UNSIGNED DEFAULT 0,
    `date_start` TIMESTAMP NULL,
    `date_end` TIMESTAMP NULL,
    `created_at` TIMESTAMP,
    `updated_at` TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE = MyISAM DEFAULT CHARSET=utf8;
```

**Comment by mikerockett** [comment]
Fixed in the above commit - please confirm that it works for you. Thanks.

**Comment by mikerockett** [comment]
@MrSnoozles - please let me know if the fix does it for you so we can close. Thanks.

**Comment by mikerockett** [comment]
Going to close this now - if you are still experiencing the issue, please re-open. Thanks.

**Comment by thetuningspoon** [comment]
I'm having the same issue and the latest commit did not resolve it.

**Comment by mikerockett** [comment]
@thetuningspoon what exceptions are you getting?

**Comment by thetuningspoon** [comment]
Module reported error during install (ProcessJumplinks): SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'


Failed to init module: ProcessJumplinks - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'icare.process_jumplinks' doesn't exist

**Comment by MrSnoozles** [comment]
Had the same problem with mysql 5.7. Will try to submit a PR this weekend. Sorry it took so long. :)

**Comment by mikerockett** [comment]
There seems to be a timestamp issue between versions - there was a reason I changed it, just can't remember exactly what it was.

@MrSnoozles I'd appreciate that very much as I'm actually not sure what the correct approach here is. I left the default out so the timestamp fields could be populated by the [`insert` statement](https://github.com/rockettpw/jumplinks/blob/master/ProcessJumplinks.module.php#L156). I'm not using MySQL though, so didn't pick up on the issue again.

**Comment by mikerockett** [comment]
@thetuningspoon Please see if #17 fixes this for you.

**Comment by thetuningspoon** [comment]
Fixed, thanks!

**Comment by mikerockett** [comment]
Excellent, closing. 👍
